import os
import json
import requests
import subprocess
import time
from pydub import AudioSegment

class AI_Video_Automator:
    def __init__(self, comfy_url, workflow_json):
        self.comfy_url = comfy_url
        self.workflow_path = workflow_json
        self.temp_dir = "temp_processing"
        self.clips_dir = "generated_clips"
        
        # Create folders
        for folder in [self.temp_dir, self.clips_dir]:
            if not os.path.exists(folder):
                os.makedirs(folder)

    def run_pipeline(self, user_input):
        """
        Main Function: User se data leta hai aur final video return karta hai.
        user_input structure:
        {
            "audio_file": "path/to/audio.mp3",
            "avatar_image": "path/to/avatar.png",
            "requirements": {
                "subtitles": True,
                "subtitle_style": "yellow_bold", # Logic in FFmpeg
                "quality": "4K" # 720p, 1080p, 4K, 8K
            }
        }
        """
        print("🚀 Pipeline Started...")

        # 1. Audio Segmentation (Chunking)
        audio_chunks = self._split_audio(user_input['audio_file'])

        # 2. Load Workflow Template
        with open(self.workflow_path, 'r') as f:
            workflow = json.load(f)

        # 3. Loop: Generate Clips via ComfyUI
        generated_clips = []
        for i, chunk in enumerate(audio_chunks):
            print(f"🎬 Generating Clip {i+1}/{len(audio_chunks)}...")
            clip_path = self._generate_single_clip(workflow, chunk, user_input['avatar_image'], i)
            if clip_path:
                generated_clips.append(clip_path)

        # 4. Stitching (Joining all clips)
        base_video = "base_joined_video.mp4"
        self._stitch_clips(generated_clips, base_video)

        # 5. Post-Processing (Subtitles & Upscaling)
        final_output = "final_output_ready.mp4"
        self._apply_final_touch(base_video, user_input['requirements'], final_output)

        print(f"✅ SUCCESS! Final Video Ready: {final_output}")
        return final_output

    def _split_audio(self, audio_path):
        print("✂️ Splitting Audio into 10s chunks...")
        audio = AudioSegment.from_file(audio_path)
        chunks = []
        for i, start_ms in enumerate(range(0, len(audio), 10000)):
            chunk = audio[start_ms:start_ms + 10000]
            path = f"{self.temp_dir}/chunk_{i}.mp3"
            chunk.export(path, format="mp3")
            chunks.append(path)
        return chunks

    def _generate_single_clip(self, workflow, audio_chunk, avatar, index):
        # Update Workflow with current chunk and avatar
        workflow['15']['inputs']['audio'] = audio_chunk # Replace '15' with your real Load Audio Node ID
        workflow['1']['inputs']['image'] = avatar       # Replace '1' with your real Load Image Node ID
        
        # Send to ComfyUI API
        payload = {"prompt": workflow}
        response = requests.post(f"{self.comfy_url}/prompt", json=payload)
        
        if response.status_code == 200:
            # NOTE: In real production, you need a loop to poll 
            # the websocket to wait for the file to be saved in the output folder.
            print(f"   Clip {index} prompt sent. Waiting for generation...")
            time.sleep(20) # Temporary placeholder for waiting
            return f"output/clip_{index}.mp4" 
        return None

    def _stitch_clips(self, clips, output_name):
        print("🔗 Stitching all clips together...")
        with open("list.txt", "w") as f:
            for clip in clips:
                f.write(f"file '{clip}'\n")
        subprocess.run(f"ffmpeg -f concat -safe 0 -i list.txt -c copy {output_name}", shell=True)

    def _apply_final_touch(self, input_video, req, output_name):
        print(f"✨ Applying Final Touches (Quality: {req['quality']}, Subtitles: {req['subtitles']})...")
        
        # Command construction
        cmd = f"ffmpeg -i {input_video}"
        
        # Add Subtitles if required
        if req['subtitles']:
            # Logic: FFmpeg uses the .ass file generated by Whisper
            cmd += " -vf \"subtitles=subtitles.ass\""
        
        # Add Scaling (Quality)
        if req['quality'] == '4K':
            cmd += " -vf scale=3840:2160"
        elif req['quality'] == '1080p':
            cmd += " -vf scale=1920:1080"
        
        cmd += f" -c:v libx264 -preset fast {output_name}"
        subprocess.run(cmd, shell=True)

# ================= TESTING THE AGENT =================
if __name__ == "__main__":
    # This is what your Frontend will send to the Handler
    user_request = {
        "audio_file": "my_long_voice.mp3",
        "avatar_image": "my_avatar.png",
        "requirements": {
            "subtitles": True,
            "subtitle_style": "yellow",
            "quality": "4K"
        }
    }

    # Initialize with your RunPod ComfyUI URL
    agent = AI_Video_Automator(comfyui_url="http://YOUR_RUNPOD_IP:8188", 
                               workflow_json="workflow_api.json")
    
    # Start the magic
    agent.run_pipeline(user_request)